### ISSUE TITLE
Hello friend :)

### ISSUE THREAD

**Issue by asystentka-jolka** [mariusz-ostoja-swierczynski/tech-controllers#1]
Cześć  Mariusz,

nie wiem czy to zbieg okoliczności czy może słyszałeś o naszym projekcie.

Nasi użytkownicy zgłosili potrzebę dodania integracji z Tech-Sterowniki:
https://ai-speaker.discourse.group/t/emodul-pl-tech-sterowniki-pl-integracja/895

Zasady odnoście dodawania nowych rzeczy w projekcie mamy takie, że:
1. Nie przyjmujemy pomysłów od użytkowników na nowe funkcjonalności niepopartych kwotą - żeby wyeliminować niepotrzebne pomysły
2. Nie przyjmujemy żadnych nieoficjalnych dostępów do API producentów, integracje oparte na (hack-ach i scrapingu)
3. Jak ktoś zakoduje/doda integrację zgłoszoną jako pomysł do AI-Speaker, to dostaje gratyfikację od zgłaszających pomysł + drugie tyle od AI-Speaker

Nie wiem  na jakim etapie jest Twoja integracja i jakie masz plany z nią związane - czy chcesz ją weryfikować w HA i oficjalnie dodać? Jeżeli tak to poczekamy na wydanie w HA (mamy w projekcie całe HA + nasze dodatkowe integracje + integracje przydatne w Polsce ale nie dodane do HA np. ExtaLife).

Jeżeli Twoja integracja spełnia nasze wymogi i byłbyś zainteresowany dodaniem do AI-Speaker to daj proszę znać.
Przed dodaniem do naszego repo, będziemy chcieli zmiany licencji na Apache 2.0 license (taka sama jak ma HA, przyjazna dla biznesu - bo jesteśmy firmą) i możemy dodać Ci dostęp do naszego repo jako komitera - żebyś dodał tam integrację.

Tu jest nasze repozytorium: 
https://github.com/sviete

A tu więcej o projekcie:
https://ai-speaker.com/

Daj proszę znać co myślisz. Możesz pisać tu, na forum albo na emaila info@ai-speaker.com 
Miłego dnia :)

**Comment by mariusz-ostoja-swierczynski** [comment]
Cześć Jolka,

Dziękuję za kontakt i bardzo mi miło, że mój projekt tak szybko się rozniósł po sieci:) Nie słyszałem o Waszym projekcie i szczerze nie planowałem, żadnych innych integracji niż dla HA. Zrobiłem to głównie z własnej potrzeby, no i widać, projekt spotkał się z dużym zainteresowaniem.

Wracając do propozycji, niestety są trzy powody dla których raczej będzie to nie możliwe:
* Robię to głównie po godzinach, hobbistycznie, a że tych wolnych godzin mam tylko kilka w tygodniu, to ograniczę się do integracji z HA, którego używam.
* Posiadam jedynie jeden sterownik L-8, z którym łatwo mi testować, chociaż tutaj może z pomocą społeczności można by coś pokombinować.
* No ale największy problem jest taki, że API producenta do którego mam dostęp na chwilę obecną wspiera jedynie te sterowniki: L-7, L-8, WiFi 8S, ST-8S WiFi

Planuję się skontaktować z producentem, może coś podpowie i podzieli się, wówczas może coś się zmieni w temacie.

Pozdrawiam serdecznie, Mariusz
