### ISSUE TITLE
[Bug]: Migration handler not found for entry Ogrzewanie for tech

### ISSUE THREAD

**Issue by daroga0002** [mariusz-ostoja-swierczynski/tech-controllers#106]
### The problem

After updating to version 2.4.0 I get:

```
2024-08-01 13:06:32.390 ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry Ogrzewanie for tech
```

![image](https://github.com/user-attachments/assets/d1c165a4-7fca-4bc0-a4b0-cb0d68225dca)

Reverting code doesnt help.

### What version of Tech Controllers integration has the issue?

v2.4.0

### What version of Home Assistant Core has the issue?

core-2024.7.4

### What was the last working version of Tech Controller integration?

2.3.1

**Comment by anarion80** [comment]
Sigh. I had the same and just removed the integration and added again. Not sure yet why this happens.

This did not happen when testing in dev container...

**Comment by daroga0002** [comment]
Yup, I got fix for this for now (give me 2-3 minutes).

**Comment by daroga0002** [comment]
It was working in dev container becuase probably you tested same as me on new config flow by creating from scratch. 
In existing integration it require some handling.

I added for now some workaround there, but we will need to handle it in more stable way. Also I will add PR template to remember about this kind of testing scenario in future.
