### ISSUE TITLE
[Bug]: Fan percentage (txtid) is missing unit of measure

### ISSUE THREAD

**Issue by ZdenekM** [mariusz-ostoja-swierczynski/tech-controllers#112]
### The problem

Fan value is displayed using colored strips. I think it might be because there is no unit of measurement set. I made a template sensor helper that takes this value and sets the unit of measurement, and the helper is displayed correctly.

![Snímek obrazovky z 2024-09-17 08-37-16](https://github.com/user-attachments/assets/a395f34e-ea52-4f61-ad80-08a9ad91047c)

![Snímek obrazovky z 2024-09-17 08-48-56](https://github.com/user-attachments/assets/edc4ce7d-454c-4131-b195-3ef4d1d91e07)

### What version of Tech Controllers integration has the issue?

2.4.0

### What version of Home Assistant Core has the issue?

2024.9.2

**Comment by anarion80** [comment]
It is clearly a bug, I will push a fix later today.

**Comment by anarion80** [comment]
Fixed in [v2.5.0](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/releases/tag/v2.5.0)

**Comment by ZdenekM** [comment]
Great, thanks!
