### ISSUE TITLE
[Bug]: Migration Error

### ISSUE THREAD

**Issue by jontofront** [mariusz-ostoja-swierczynski/tech-controllers#118]
### The problem

Logger: homeassistant.config_entries
Source: config_entries.py:935
First occurred: September 20, 2024 at 10:21:50 PM (1 occurrences)
Last logged: September 20, 2024 at 10:21:50 PM

Migration handler not found for entry L-4 for tech

### What version of Tech Controllers integration has the issue?

v2.5.0

### What version of Home Assistant Core has the issue?

core-2024.9.2

### What was the last working version of Tech Controller integration?

2.4.0

### Diagnostics information

![image](https://github.com/user-attachments/assets/073f8c08-023d-4eb7-9024-d8c17acca503)

### Anything in the logs that might be useful for us?

```text
after insert in configuration:
"  logs:
    # log level for a tech custom integration
    custom_components.tech: debug"

"2024-09-23 20:23:06.124 ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry L-4 for tech"
```

**Comment by daroga0002** [comment]
This is known issue and documented in 2.3.1 release https://github.com/mariusz-ostoja-swierczynski/tech-controllers/releases/tag/v2.3.1


Please remove devices and add them again.

**Comment by jontofront** [comment]
ok thanks it's works
