### ISSUE TITLE
[Feat]: brak termostatu

### ISSUE THREAD

**Issue by mankog** [mariusz-ostoja-swierczynski/tech-controllers#119]
### The request

Utworzyłem integrację, ale nie pojawił mi się żaden termostat. Chciałbym za jego pomocą zmieniać zadana temperaturę zaworu mieszającego.
Sterownik ST-801 zPID, rozszerzenie o modul I-1m

**Comment by anarion80** [comment]
Po pierwsze trzeba sprawdzić co jest widoczne i dostępne dla tego zestawu w https://emodul.eu.

A potem sprawdzić i podesłać JSON wg opisu: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/blob/main/CONTRIBUTING.md

wtedy będziemy wiedzieć co jest w ogóle możliwe.

**Comment by daroga0002** [comment]
Wydaje mi sie ze te termostaty sa zarzadzane prze Menu API

`/users/{Buser_id}/modules/{module_udid}/menu/{menu_type}/{pin}`

czyli któryś z tych odpowiedzi:
- MI
- MS
- MU
- MP


![image](https://github.com/user-attachments/assets/33dddf96-224f-43ec-a321-f23269f03c9f)



Niestety dokumentacja API jest słaba wiec mozna to tylko metoda prób i błędów rozpracować.

**Comment by mankog** [comment]
Dziękuję za pochylenie się nad tematem.
Integracja pokazała mi taka encję

sensor.stalmark_temp_zadana_co

Wskazuje ona temperaturę, która jest ustawiona na zaworze. Jeśli mozna by
nią zmieniać to wtedy łatwiej kontrolować temperatury w domu.

Spróbuję jeszcze wyciągnąć  logi wg instrukcji.
Tylko ze jestem początkujący  to może potrwac

śr., 25 wrz 2024, 16:09 użytkownik Dawid Rogaczewski <
***@***.***> napisał:

**Comment by anarion80** [comment]
Duplicate of https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/141.
