### ISSUE TITLE
[Bug]:  valve pump attribute value incorrect

### ISSUE THREAD

**Issue by space9911** [mariusz-ostoja-swierczynski/tech-controllers#134]
### The problem

Proszę o pomoc w braku danych zaworu mieszającego .
bardzo dziękuje za integracje - świetna robota.
 
![emodul](https://github.com/user-attachments/assets/728e627f-c856-436d-a639-2cd3fa6378a5)
![ha](https://github.com/user-attachments/assets/aaa9699d-d620-45c3-9ea5-176b037bce3b)
![json](https://github.com/user-attachments/assets/c0c5bfcb-7266-468d-a71c-64605f3199ef)

### What version of Tech Controllers integration has the issue?

ST-9730

### What version of Home Assistant Core has the issue?

 Core 2024.11.3

**Comment by space9911** [comment]
W integracji HA nie widzi włączonej valuepomp natomiast emodul włączona , również w Json jest na "1" jeżeli dobrze to interpretuje

**Comment by anarion80** [comment]
Ok, rozumiem, popatrzę na to.
