### ISSUE TITLE
[Bug]: pytanie techniczne

### ISSUE THREAD

**Issue by krzysztofgambus** [mariusz-ostoja-swierczynski/tech-controllers#139]
### The problem

Cześć, MAriusz mam pytanie ponieważ integracje którą pobrałem działa ale pobiera tylko sensory z zakładki HOME, a chciałbym uzyskać dostęp np do menu użytkownika w którym można zmieniać parametry pracy pompy, temp itp. Jest taka możliwość ?

### What version of Tech Controllers integration has the issue?

1

### What version of Home Assistant Core has the issue?

1

**Comment by anarion80** [comment]
Nie, obecnie funkcje z Menu nie są obsługiwane w integracji.

**Comment by krzysztofgambus** [comment]
A jest szansa żeby je oczywiście odpłatnie zintegrować

**Comment by anarion80** [comment]
Ja obecnie nie mam możliwości/czasu żeby się tym zająć. Więc raczej tylko jeśli ktoś z community wystawi PRa.
