### ISSUE TITLE
Support for tiles

### ISSUE THREAD

**Issue by mariusz-ostoja-swierczynski** [mariusz-ostoja-swierczynski/tech-controllers#15]

**Comment by mariusz-ostoja-swierczynski** [comment]
This is now done and merged to dev and will be hopefully soon merged to master.

@gszumiec I had to comment out bit of code in sensor.py:

# TODO: this sensor's ID assignment needs to be fixed as base on such ID
#  tech api doesn't return value and we get KeyError
#
# class TileValveTemperatureSensor(TileSensor):

If you have time, please look on this if you can fix it.

**Comment by maciej-or** [comment]
hi @mariusz-ostoja-swierczynski,
I've checked current dev branch. I'm not sure if it's mistake by merging or intended change but all sensors have device instances. Logically should be 1 device with multiple sensors. In my case it is 1 boiler (device) and 18 sensors.

my initial PR:
![image](https://user-images.githubusercontent.com/38075949/203645552-1d8210e1-5ade-44f2-8ca2-b0b89333c99f.png)

and current dev with my boiler:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/38075949/203646220-344b975f-e6aa-41b7-8946-a49410c52957.png">

**Comment by jontofront** [comment]
In my case dev branch works ok, 
I have 8 zones = device. One device is Boiler pump 
![image](https://user-images.githubusercontent.com/37038426/203726754-d2e07a63-995c-4dc0-87ae-83e181d4c569.png)

**Comment by maciej-or** [comment]
Well, I suppose it's wrong mapping to Home Assistant structures. You have 1 device (L4 controller) with 8 HVAC entities (zones) and 1 binary sensor or switch entity (pump). 
see: https://www.home-assistant.io/integrations/climate
Zones should have index 1-8 and belong to the same device. Imagine you have more than one L4 controller or more than one boiler. I would expect their entities will be grouped by device.
