### ISSUE TITLE
Local api?

### ISSUE THREAD

**Issue by ishioni** [mariusz-ostoja-swierczynski/tech-controllers#17]
I'm searching for solutions a house I'll be building soon, there's not a lot of them really. Is it possible tech-controllers have a local api instead of going via their cloud?

**Comment by mariusz-ostoja-swierczynski** [comment]
Unfortunately I did not find a way to access local API for tech-controllers and they didn't provide support even with this integration. This integrations is only via tech-controllers cloud API.

**Comment by ishioni** [comment]
Did you ask then about it? :)
