### ISSUE TITLE
Unable to setup integration on Version: 2021.6.6

### ISSUE THREAD

**Issue by laurynas-V** [mariusz-ostoja-swierczynski/tech-controllers#23]
Unable to setup integration to new Home-assistant setup Version: 2021.6.6. Done everything according instructions. But  can't find integration. 
<img width="534" alt="Screenshot 2021-06-26 at 13 19 29" src="https://user-images.githubusercontent.com/61992782/123510070-19b02980-d682-11eb-9ab5-44a58380a849.png">
<img width="333" alt="Screenshot 2021-06-26 at 13 20 40" src="https://user-images.githubusercontent.com/61992782/123510071-1a48c000-d682-11eb-8a93-3d0dfe197ed8.png">

<img width="348" alt="Screenshot 2021-06-26 at 13 20 53" src="https://user-images.githubusercontent.com/61992782/123510072-1ae15680-d682-11eb-8a49-169c360bc526.png">
<img width="1069" alt="Screenshot 2021-06-26 at 13 21 19" src="https://user-images.githubusercontent.com/61992782/123510074-1b79ed00-d682-11eb-9a11-88cfec6ad592.png">

**Comment by adamkac** [comment]
check this out :)
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/22

**Comment by ondrej-vereb** [comment]
Hi All,
I had the same issue. Check your logs in Configuration -> Logs. I found there a message which was saying "The custom integration 'tech' does not have a version key in the manifest file and was blocked from loading". To fix it just add a version statement in _/config/custom_components/tech/manifest.json_ .

Mine looks like this:

{
"domain": "tech",
"name": "Tech Controllers",
"version": "1.0",
"config_flow": true,
"documentation": "https://www.home-assistant.io/integrations/tech",
"requirements": ["tech"],
"dependencies": [],
"codeowners": [
"@mariusz.ostoja-swierczynski"
]
}

After a reboot of the Haas integration appears in search it's possible to install and works well. 

Regards
Ondrej
