### ISSUE TITLE
TECH: ST-8s WIFI (v.1.0.4) stopped working after HA restart

### ISSUE THREAD

**Issue by Kowalus** [mariusz-ostoja-swierczynski/tech-controllers#3]
Cześć Mariusz.

Mam zrobiona integracje Tech. Połączona jest z modułem TECH: ST-8s WIFI (v.1.0.4). 
Problem polega na tym że działało wszystko fajnie ale po restarcie HA przestało działać. 
Usunąłem integracje ponowienie połączyłem i pokazuje ze wszystko przebiegło pomyślnie.
Ale moduł nie pokazuje encji. 
Wiec zalogowałem się na inne konto z modułem  TECH: WiFi 16S (v.1.0.16) na którym pokazywało 16 encji
To znowu wziąłem zalogowałem się na inne konto tez z modułem TECH: WiFi 16S (v.1.0.16) i tu już nie pokazywało encji.
Prosiłbym o jakieś rady.

Pozdrawiam

**Comment by mariusz-ostoja-swierczynski** [comment]
Cześć Kowalus,

Dziękuję za zgłoszenie, ciekawa sprawa, że po restarcie przestało działać. Aby pomóc mi zdebugować problem, potrzebowałbym logi i wówczas możemy myśleć co dalej. W "contributing guidelines" przygotowałem instrukcję jak te logi najłatwiej wyciągnąć:
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/blob/main/CONTRIBUTING.md

Pozdrawiam, Mariusz

**Comment by Kowalus** [comment]
Witam.
Nie umie tego wytłumaczyć ale po zmianie oprogramowania do wersji  (v.1.0.5) wszystko działa.
Problem jest ze po wgraniu nowszej wersji oprogramowania wszystko trzeba na nowo rejestrować :)
Moge powiedzieć ze moduł TECH: ST-8s WIFI (v.1.0.5) działa,

**Comment by mariusz-ostoja-swierczynski** [comment]
Świetne info, dzięki! I tak jest, też robiłem update oprogramowania sterownika, i wówczas wszystko jest resetowane. Tak to wymyślił producent. Zamykam ticket.

**Comment by Kowalus** [comment]
Z TECH: ST-16s WIFI tylko tez wersja oprogramowania (v.1.0.5) działa
