### ISSUE TITLE
Cannot connect to integration - L4-WiFi (v.1.1.10)

### ISSUE THREAD

**Issue by Drakenzo** [mariusz-ostoja-swierczynski/tech-controllers#32]
Hello, 

while trying to add integration I'm facing below error:
![image](https://user-images.githubusercontent.com/64210551/194054207-e9a24515-cac4-4b0a-a86f-603170f55d5d.png)

Credential are good - when I'm giving wrong pass it says "Incorrect Password"
Please find below part of a logfile:

Traceback (most recent call last):
  File "/config/custom_components/tech/config_flow.py", line 53, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/tech/config_flow.py", line 26, in validate_input
    if not await api.authenticate(data["username"], data["password"]):
  File "/config/custom_components/tech/tech.py", line 65, in authenticate
    result = await self.post(path, post_data)
  File "/config/custom_components/tech/tech.py", line 56, in post
    raise TechError(response.status, await response.text())
custom_components.tech.tech.TechError: (400, '{"error":"Bad Request"}')

Have anyone faced the same issue and have a solution?

**Comment by Drakenzo** [comment]
Solution to my problem: https://github.com/MichalKrasowski/tech-controllers/pull/13/commits/4c2c3ec57b339efe12d83bf5d6179c6c8545f60f

**Comment by mariusz-ostoja-swierczynski** [comment]
This is now merged to master and dev branches. @Drakenzo please test it.

Furthermore dev branch contains now few new fat features:
#7 
#15 
#24 

Please have a look. Cheers, Mariusz
