### ISSUE TITLE
Invalid config: The following integrations and platforms could not be set up: tech

### ISSUE THREAD

**Issue by Pxvvxp** [mariusz-ostoja-swierczynski/tech-controllers#34]
Few days ago I had to restart my HA from Backup and TECH stopped working. I tried to reinstall integration but it seems repo is outdated.

**In notification I see:**
> **Invalid config**
> _The following integrations and platforms could not be set up: tech (Show logs)_

**When I am trying to reinstall TECH integration:**
> **Error**
> _Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble_

**In logs I see:**
> _Setup failed for custom integration tech: Requirements for tech not found: ['tech']._
> _6:17:00 PM – (ERROR) setup.py_
> _Unable to install package tech: ERROR: Could not find a version that satisfies the requirement tech (from versions: none) ERROR: No matching distribution found for tech_
> _6:17:00 PM – (ERROR) util/package.py - message first occurred at 6:16:46 PM and shows up 3 times_
> 
> 2_022-10-18 18:17:00.751 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package tech: ERROR: Could not find a version that satisfies the requirement tech (from versions: none)_
> _ERROR: No matching distribution found for tech_
> _2022-10-18 18:17:00.754 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration tech: Requirements for tech not found: ['tech']._

Anyone else having this problem or someone know how to fix this?

![image](https://user-images.githubusercontent.com/34990103/196486708-6917859f-bc27-476c-b83b-d87eafcd7420.png)
![image](https://user-images.githubusercontent.com/34990103/196487813-0e5b864e-6c6f-46c9-8948-2bd281bf35ae.png)

**Comment by Pxvvxp** [comment]
For others who may get this error here is a solution:
Duplicate of https://github.com/MichalKrasowski/tech-controllers/issues/11
You need to remove tech requirement line from manifest.json as it is referencing a non existent pypi package.

**Comment by mariusz-ostoja-swierczynski** [comment]
This is now merged to master and dev branches. @Pxvvxp  please test it.

Furthermore dev branch contains now few new fat features:
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/7
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/15
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/24

Please have a look. Cheers, Mariusz
