### ISSUE TITLE
No icons in Devices view

### ISSUE THREAD

**Issue by jontofront** [mariusz-ostoja-swierczynski/tech-controllers#37]
@mariusz-ostoja-swierczynski 

Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

There are no icons:

![image](https://user-images.githubusercontent.com/37038426/202700263-0c48dc62-f626-443f-a50f-a2ee5451eafd.png)

**Comment by mariusz-ostoja-swierczynski** [comment]
@jontofront thank you for reporting this. Could you please also check logs and post them here if you see any errors for Tech component?

**Comment by jontofront** [comment]
ok, thanks, I will check logs,  but look what i found:
https://github.com/micles123/tech-controllers/commits?author=micles123
This guy split sensors , maybe we can merge both codes?
![image](https://user-images.githubusercontent.com/37038426/202715580-81b5b467-0089-4bbe-82a1-8adcce166939.png)

**Comment by jontofront** [comment]
> @jontofront thank you for reporting this. Could you please also check logs and post them here if you see any errors for Tech component?

@mariusz-ostoja-swierczynski  here you go:
```
2022-11-18 15:35:56.352 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tech platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tech/sensor.py", line 66, in async_setup_entry
[
File "/config/custom_components/tech/sensor.py", line 67, in <listcomp>
ZoneTemperatureSensor(
File "/config/custom_components/tech/sensor.py", line 89, in __init__
self._temperature = device["zone"]["currentTemperature"] / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by mariusz-ostoja-swierczynski** [comment]
> ok, thanks, I will check logs, but look what i found: https://github.com/micles123/tech-controllers/commits?author=micles123 This guy split sensors , maybe we can merge both codes? ![image](https://user-images.githubusercontent.com/37038426/202715580-81b5b467-0089-4bbe-82a1-8adcce166939.png)

I will be glad to do merge of this new sensors if @micles123 creates pull request.

**Comment by mariusz-ostoja-swierczynski** [comment]
@jontofront I pushed fix for this in Dev. Please download newest version (you can download only sonsor.py file) and retest it.

Cheers, Mariusz

**Comment by jontofront** [comment]
I had after integration new pop up with Area cool.

OK there are no errors in error log but Ithink it bad pictures path:
![image](https://user-images.githubusercontent.com/37038426/202731952-864a9787-ba2d-4ed9-be1d-92673979eb1b.png)

![image](https://user-images.githubusercontent.com/37038426/202733322-0450dcb6-2801-442c-aaf3-62fa2dabf662.png)

I have only one error but I think it's not from tech integration

![image](https://user-images.githubusercontent.com/37038426/202733083-e96ce7ad-6900-42cb-bbf5-9fa4830ee1ce.png)

**Comment by mariusnauj** [comment]
@jontofront hi,

Whats new if I'll change sensor.py file?

**Comment by mariusnauj** [comment]
Hello @mariusz-ostoja-swierczynski 
I installed dev integration, all works fine. But there is no battery sensor. Maybe you planning to add it?

**Comment by jontofront** [comment]
> Hello @mariusz-ostoja-swierczynski I installed dev integration, all works fine. But there is no battery sensor. Maybe you planning to add it?
@mariusnauj In HA device there Icons?

**Comment by jontofront** [comment]
> @jontofront no, it witout icons. But what about battery ?

I aksed my friend to code it. He is work on php, but he do somthing. I am testing new version if it work we will merge to @mariusz-ostoja-swierczynski dev branch

@mariusnauj https://github.com/AkiraJager/tech-controllers

**Comment by mariusnauj** [comment]
Hello @jontofront,
Can I use this integration of your friend https://github.com/AkiraJager/tech-controllers ? It's working?

**Comment by jontofront** [comment]
> Hello @jontofront, Can I use this integration of your friend https://github.com/AkiraJager/tech-controllers ? It's working?

yes I am using it
