### ISSUE TITLE
Unregistered zones issue

### ISSUE THREAD

**Issue by gszumiec** [mariusz-ostoja-swierczynski/tech-controllers#4]
Cześć Mariusz,

Pobrałem Twój kod. U mnie pokazywało 32 strefy na 2 listwach L-9 przy ładowaniu, ale niestety wawalało się bo na niezarejestrowanych strefach currentTemperature zwracał none, co dawało błąd przy dzieleniu przez 10.

Poprawiłem kod i dorzuciłem parę zmian od siebie

Wgram kod i możesz sobie zobaczyć zmiany.

w L-9 oprócz zones jest jeszcze tiles i odpowiada za czujniki podłączne radiowo

**Comment by mariusz-ostoja-swierczynski** [comment]
Świetnie, że to zidentyfikowałeś. Ludzie na grupie Facebookowej Home Assistant Polska zgłaszali ten błąd, ale nie mogłem tego zreprodukować bez logów. Poproszę o Pull Request i chętnie wciągnę Twoje poprawki.

**Comment by gszumiec** [comment]
I think that more important than Heating Controller L-9r (v1.0.2) is managing panel M-9 (v1.0.12)
I have second heating controller on 2nd floor but it's hard to get there, so I will check version during next service.

**Comment by gszumiec** [comment]
Stawiam środowisko testowe, nie chcę robić iteracji na produkcyjnej instancji, jak skończę to przetestuję i zrobię PR.

**Comment by gszumiec** [comment]
PR created #5

**Comment by mariusz-ostoja-swierczynski** [comment]
PR tested with my setup and it works! Thanks Grzegorz. PR #5 merged to main branch.

**Comment by mariusz-ostoja-swierczynski** [comment]
@gszumiec Pytanie, jak byłeś w stanie pokazać 32 strefy z dwóch listw, skoro integracja do tej pory wspierała tylko obsługę jednej listwy, pierwszej zwaracanej przez API? Czy sam przerobiłeś kod? Właśnie zaimplementowałem to wsparcie dla wielu kontrolerów na raz #7 oraz Twój błąd zgłoszony rozwiązałem w inny sposób, bo wystempował też w innych sytuacjach #6 .

Mógłbyś przetestować wersję z brancha "dev", gdzie jest zaimplementowana obsługa wielu kontrolerów na raz?

**Comment by gszumiec** [comment]
w tym rzecz, że do jednego kontrolera jest wpiętych wiele listw i to jest obsługiwane by default. Po prostu dla kontrolera listwy są podłączone szeregowo i nie znalazłem informacji w payloadzie o przypisaniu zone do konkretnej listwy. Jest parentId dla zone ale zawsze jest taki sam parentId:99

Jak przetestuję to dam Ci znać
Możesz też sprawdzić na koncie testowym username: test password: test

**Comment by gszumiec** [comment]
sprawdziłem u mnie, dev działa poprawnie, Ładują się encję. Ale mam tylko jeden kontroler

**Comment by gszumiec** [comment]
Na koncie test:test pojawiają się wszystkie kontrolery po załadowaniu integracji, ale tylko 8 stref z Listwy L-8 demo

**Comment by mariusz-ostoja-swierczynski** [comment]
Dzięki wielkie za testy!

Ja właśnie testowałem tona koncie test/test od TECH, ale tam tylko jeden kontroler ma strefy, ten L-8, pozostałe nie mają, stąd pomyślałem, że Ty musisz mieć taki podobny setup, ale teraz rozumiem, że jest inny. Niemniej jednak, dodatkowe testy zawsze są w cenie :) i napewno się przyda Twój payload #8 do analizowania.

Jeszcze jedna prośba jak mogę :) Jak wspomniałem wyżej, trochę w innym miejscu naprawiłem ten oryginalny problem z dzieleniem None / 10, więc wydaje mi się, że ten filtr na unregisteredZone, można by usunąć. Byłbyś w stanie sprawdzić, czy po usunięciu tego filtra, nie będziesz miał tego błędu zgłoszonego przez Ciebie? Proszę przetestuj to na branchu main.

Z góry dzięki!
