### ISSUE TITLE
Support for reading actuators from zone

### ISSUE THREAD

**Issue by cor73x** [mariusz-ostoja-swierczynski/tech-controllers#57]
@anarion80 re-adding in correct repo :) 

First, thank you for taking care of this integration :)

I have small request, I have few actuators on my radiators, and it would be nice to read battery level and valve open status in HA.
Can you add this?

In json file, it is in:
zones.elements.[].actuators - battery level, signal strength.
Open level: zones.elements.[].zone.actuatorsOpen (0-100%).

You can have more than one actuator in zone, but open level is same for all actuators as there is only one value in json.

In demo app it is visible here:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/3730619/17fcda26-407b-4e76-944c-ad46444d272b)
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/3730619/65b83fb1-608d-4a05-9633-64ffa6210411)

Probably those can be added as "valves" and battery level/signal strength as attributes? you are unable to control actuator from emodul, so maybe just sensors will be enough.

Thanks!

**Comment by anarion80** [comment]
@cor73x please check the proposed implementation here: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/tree/add_57

There are probably a few ways to do this, currently I chose to create a sensor for each actuator, with the same state as only one state is reported, and attributes for battery level and signal strength.

**Comment by cor73x** [comment]
@anarion80 you were so fast that I was unable to check this :) thx

**Comment by anarion80** [comment]
Well, free(-er) time during the weekend ;)
