### ISSUE TITLE
Entities and devices are getting mixed when there are more than one main module linked to account

### ISSUE THREAD

**Issue by bpawulski** [mariusz-ostoja-swierczynski/tech-controllers#58]
For detailed description see https://github.com/anarion80/tech/issues/8#issue-2197852690

[logs.zip](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/files/14669497/logs.zip)

I have anonymized the logs a little bit by replacing user id and token. Hope it will not be a problem with fixing the integration

**Comment by anarion80** [comment]
Thanks! Just in case can you also post your:

`core.device_registry`
`core.entity_registry`
`core.config_entry`

files from <your ha config folder>/.storage
?
You can just copy only what is related to tech domain.

**Comment by bpawulski** [comment]
As requested:

[core_logs.zip](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/files/14670382/core_logs.zip)

**Comment by anarion80** [comment]
@bpawulski Please check the potential fix from this branch: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/tree/fix_58 (just download zip and replace in your HA instance).

The fix is rather simple, but migration is a nightmare and impossible to be done fully. So please try with migration first, if that does not work, then just remove the controller and add again.

**Comment by bpawulski** [comment]
Migration wasn't working so i removed everything and started from scrach. There is still problem with non existing sensor "Temperatura zewnętrzna" connected to "Gora" hub, showing constant -200. The outside temp sensor is connected only to "Dol" hub wich shows correct readings. Maybe there is some way to discover that the actual sensor deasn't exist there and readings are just rubbish.

**Comment by anarion80** [comment]
Thanks. The outside temp sensor is likely this one:

```json
"tiles": [{
            "id": 88888,
            "parentId": 0,
            "type": 1,
            "menuId": 0,
            "orderId": null,
            "visibility": true,
            "params": {
                "description": "Temperature sensor",
                "workingStatus": false,
                "txtId": 795,
                "value": -2000,
                "batteryLevel": null,
                "signalStrength": null
            }
```

which is indeed reporting -200 from the API, but is also showing `workingStatus: false`. So looks like such sensors need to be excluded.

**Comment by anarion80** [comment]
Do you perhaps have any logs from the non-working migration?

**Comment by bpawulski** [comment]
yhhh, no i don't collected them. And now after so many restarts all are overwritten.

**Comment by anarion80** [comment]
Ok, ok.

**Comment by bpawulski** [comment]
@anarion80 just a small improvement. How about creating HA entity names based on combination of hub name and zone name -> if hub is called "Gora" and zone is called "Łazienka" do sensor.gora_lazienka_temperature etc. In this case when i have bathroom at both floors i wouldn't have to change zone name to distinguish it in HA. Ideally this might be a config option, for people with single hub such naming might not be convenient, but i believe for the ones with multiple hubs this will be useful.

**Comment by anarion80** [comment]
Please open a separate issue for tracking that.
