### ISSUE TITLE
Climate entities not created

### ISSUE THREAD

**Issue by PeterSuly** [mariusz-ostoja-swierczynski/tech-controllers#60]
Hi @anarion80, after migration to 2.0.0, there are all zone represented as devices with coresponding temperatures and batteries. There are no climate entities for me so temperature cannot be changed. This errors are present in my logs. My controller is L-4 Wifi

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:368
Integration: Klimatizácia ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 21:18:54 (2 occurrences)
Last logged: 21:23:06

Error while setting up tech platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 315, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 670, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tech/climate.py", line 157, in supported_features
    | ClimateEntityFeature.TURN_ON
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_ON
``` 

```
Podrobnosti záznamu (CHYBA)
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Klimatizácia ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 21:18:54 (2 occurrences)
Last logged: 21:23:06

Error adding entities for domain climate with platform tech
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 315, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 670, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tech/climate.py", line 157, in supported_features
    | ClimateEntityFeature.TURN_ON
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_ON
```

**Comment by anarion80** [comment]
Thanks for the issue @PeterSuly . Can you please take a look at newly updated [contributing guide](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/blob/main/custom_components/tech/CONTRIBUTING.md) and provide some more logs according to that guide? Especially the JSON file for this type of controller would be useful. Also, what is your HA core version?

**Comment by PeterSuly** [comment]
@anarion80 
Sadly, i already rollbacked to old version of integration. All i have is home assistant log from time when i was analyzing what is wrong and emodule json response from getting zones. Hopefully it will be enough, work you done with v2 update is great !

[home-assistant_tech_2024-03-21T20-41-59.218Z.log](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/files/14720676/home-assistant_tech_2024-03-21T20-41-59.218Z.log)
[emodule_response.json](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/files/14720678/emodule_response.json)

**Comment by anarion80** [comment]
Thanks @PeterSuly. As suspected you have too old (even though relatively new 😉 ) HA version.
Currently tech controller integration requires 2024.3.0: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/blob/5353108a79c7f5c2a3aaaeaf009a0a9735f8f547/hacs.json#L7

Your problem is specifically related to this recent change in 2024.2.0 which we already implement:
https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/

With that, I suggest to upgrade HA core and try again. I will close the issue for now.

**Comment by PeterSuly** [comment]
Thanks, i will try to update asap

**Comment by PeterSuly** [comment]
@anarion80 After everything is updated, it's working again. Thanks.

**Comment by chappaai** [comment]
Having the same problem on 2023.10.3 running LX-WiFi. 
I will update and let you know about the results. Thanks.

**Comment by chappaai** [comment]
I confirm, the fix is also working for me.
