### ISSUE TITLE
Create HA entity name based on hub and zone names 

### ISSUE THREAD

**Issue by bpawulski** [mariusz-ostoja-swierczynski/tech-controllers#61]
just a small improvement. How about creating HA entity names based on combination of hub name and zone name -> if hub is called "Gora" and zone is called "Łazienka" do sensor.gora_lazienka_temperature etc. In this case when i have bathroom at both floors i wouldn't have to change zone name to distinguish it in HA. Ideally this might be a config option, for people with single hub such naming might not be convenient, but i believe for the ones with multiple hubs this will be useful.

**Comment by bpawulski** [comment]
<img width="1420" alt="Screenshot 2024-04-04 at 20 30 47" src="https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/148430024/f5be39ea-fe8e-4bb0-818d-659a9bb96fc8">
<img width="1395" alt="Screenshot 2024-04-04 at 20 30 57" src="https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/148430024/a551a824-fc2f-49a5-9e0c-4fa18d58e4c4">
The only thing i can see have changed is the name of outside temp sensor which accommodates the hub name. All zone names stayed the same. As well as i still have not available outside temp sensor connected to "Gora" hub.

**Comment by daroga0002** [comment]
In general I think we should stick this:

```
"The entity's name property only identifies the data point represented by the entity, and should not 
include the name of the device or the type of the entity. (...) If the entity represents a single main 
feature of a device the entity should typically have its name property return None. The "main feature"
of a device would for example be the LightEntity of a smart light bulb."
```


But @bpawulski  regarding your issue screens which you showing above are devices, not entities. 

HA itself allow you to change device names:
<img width="1661" alt="image" src="https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/20227477/14425629-10e3-4e83-901f-db53711d58e8">


or even entity name:
<img width="1377" alt="image" src="https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/20227477/6fc72050-6d68-4954-9640-2c6c3797715c">



so I am little confused what real issue we trying to solve here?


Additionally in newest HA release you have additional features (for example labels) to organize things https://www.home-assistant.io/blog/2024/04/03/release-20244/

**Comment by anarion80** [comment]
Ok, there is a compromise possible here. The latest version [(please check here)](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/tree/feat_61) is not in conflict with HA guidance, as every entity implements `_attr_has_entity_name = True` and we still use HA mechanism for naming including device name when appropriate.

I added an option to check when adding controllers and include hub names in entity names:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/990b5bfd-6989-4502-929f-c14464d0bd3f)

and then if selected, we get:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/755ec625-c21d-4e4e-957f-29129243c19a)
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/733b654f-3dea-46ec-8b17-fbc9674ea509)
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/758bd563-1500-448d-88e4-035a610496a4)


By default, when not enabling this option we get:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/0ab19953-6c63-403f-99d7-2112371c8597)
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/55f5b1b7-673c-4db5-81ea-c38708a6f4a2)
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/110778c0-fa51-406e-ab81-dc6398dbd7e8)

Please note that:
1. We now use HA translation placeholders for entity names so they are translated to available languages.
    1. As a result some entities are named by combining device name + entity name and we get `sensor.external_temperature_temperature`.
2. Some entities are now without devices - as they should be.

(and all temperature entities now create devices, while only the ones that have battery or signal strength should - that needs to be addressed)

**Comment by bpawulski** [comment]
I like this approach, It works fine for me. Thanks!
