### ISSUE TITLE
Support for multiply controllers

### ISSUE THREAD

**Issue by mariusz-ostoja-swierczynski** [mariusz-ostoja-swierczynski/tech-controllers#7]
Users of TECH Controllers can own multiply controllers within one household, ex. one L-7 to control their floor heating system and other, ex. WiFi 8S to control their heaters on second floor. Currently this integration is able to handle one controller which is first returned by TECH API. 

The aim of this enhancement is to provide support for multiply controllers within one household.

**Comment by SkeLLLa** [comment]
Hi. First of all thanks for this module. If you need some testing of such configuration, I have i-3 module and L7-E.

**Comment by alevike** [comment]
Hello, 
It looks promising, i have a OPOP: ST-581v9 Premium unit - it is a pellet boiler - if you're interested to implement the support for this one i will gladly support you..

**Comment by mariusz-ostoja-swierczynski** [comment]
Hi @SkeLLLa it would be really great if you can test this out and provide feedback. This feature is already implemented and pushed to dev branch, therefore in order to test it out, you only need to change to dev branch and download the code.

**Comment by luczakrm** [comment]
Cześć, mam dwa sterowniki L-4, ale na branchu dev nadal zwracane są strefy tylko z pierwszego sterownika

**Comment by nepozs** [comment]
@luczakrm 
Projekt umarł jakiś rok temu - poszukaj po forkach, bo może ktoś utrzymuje aktywny rozwój, ale z pewnością nie pierwotny autor i nie wiemy co się stało…

**Comment by mariusz-ostoja-swierczynski** [comment]
This feature is finally done in dev branch. @SkeLLLa @luczakrm please test it out and report any issues. I will marge is to master hopefully soon.

Few words of explanations it took so long. During the development of this feature I was trying to get some simple support from Tech (answer on their APIs), but they didn't provide it although they promised it.  After long time of reminding myself to them, winter was over and I lost both time and motivation. This winter I found out how many people were interested in this integration and even some people put effort for further development of this integration and so I regained bit of motivation. Anyway I don't have anything against forking this repo and moving forward if I lost it again :)

**Comment by SkeLLLa** [comment]
@mariusz-ostoja-swierczynski thanks.

I've also checked both versions yours and forked one. And it doesn't find the second controller. It just finds only `i-3`, but misses `L7-E`.
I think it just gets the first module from array `https://emodul.eu/frontend/account_modules` request. Module order is assigned during registration and in Tech API there's no method that could change it.

```
{
  "modules": [
    {
      "id": 0,
      "default": true,
      "name": "Boiler room",
      "email": "***",
      "type": "installation",
      "controllerStatus": "active",
      "moduleStatus": "active",
      "additionalInformation": "",
      "phoneNumber": "Boiler room",
      "zipCode": "01000",
      "tag": null,
      "country": "***",
      "gmtId": 30,
      "gmtTime": "1",
      "postcodePolicyAccepted": true,
      "style": "installation",
      "version": "TECH: i-3 (v.1.2.3)",
      "company": "tech"
    },
    {
      "id": 1,
      "default": false,
      "name": "Rooms",
      "email": "***",
      "type": "zones_controller",
      "controllerStatus": "active",
      "moduleStatus": "active",
      "additionalInformation": "",
      "phoneNumber": "",
      "zipCode": "01000",
      "tag": null,
      "country": "***",
      "gmtId": 30,
      "gmtTime": "1",
      "postcodePolicyAccepted": true,
      "style": "zones",
      "version": "TECH: L-7E (v.1.0.6)",
      "company": "tech"
    }
  ],
  "selectedModuleIndex": 0,
  "style": "defro"
}
```

**Comment by chudystg** [comment]
Hi, when a multi-controller version is planned?

**Comment by chudystg** [comment]
I have the dev version of the addon. Added my 5 controllers and the name is ok but the entities only from the first one

TECH: L4-WiFi (v.1.1.10) TECH: L4-WiFi (v.1.1.10) TECH: L-8 (v.3.0.21) TECH: L4-WiFi (v.1.1.10) TECH: L4-WiFi (v.1.1.10) 

![Screen Shot 2023-01-10 at 18 22 43 PM](https://user-images.githubusercontent.com/101641915/211619704-6efca07a-0251-4c8e-ab28-5d9e6aae77a1.png)

**Comment by mdrobniu** [comment]
What is the status of this feature? Is it implemented? Or only works from dev branch? 
I've been installing from master and can only use one module and I have 3 at my household.

**Comment by krypton9208** [comment]
i check today version from dev - is not working with second controller - even when i have other accounts for both of my L-7 controllers ... 

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:612
Integration: Klimat (documentation, issues)
First occurred: 17:13:32 (6 occurrences)
Last logged: 17:13:32

Platform tech does not generate unique IDs. ID 102 already exists - ignoring climate.sypialnia
Platform tech does not generate unique IDs. ID 103 already exists - ignoring climate.garaz
Platform tech does not generate unique IDs. ID 104 already exists - ignoring climate.wc
Platform tech does not generate unique IDs. ID 105 already exists - ignoring climate.wiatrolap
Platform tech does not generate unique IDs. ID 106 already exists - ignoring climate.lazienka
```
