### ISSUE TITLE
[Bug]: thermostat temperature increase/decrease is only by 0,5 degree

### ISSUE THREAD

**Issue by daroga0002** [mariusz-ostoja-swierczynski/tech-controllers#71]
### The problem

Thermostat feature allowing only to increase/decrease temperature by 0,5 degreee.

### What version of Tech Controllers integration has the issue?

v2.1.0

### What version of Home Assistant Core has the issue?

doesnt matter

**Comment by anarion80** [comment]
Fixed by https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/72
