### ISSUE TITLE
[Feat]: tile temperature sensor -> add batteryLevel and signalStrength 

### ISSUE THREAD

**Issue by daroga0002** [mariusz-ostoja-swierczynski/tech-controllers#76]
### The request

Tile temperature sensor currently support only temperature. 

https://github.com/mariusz-ostoja-swierczynski/tech-controllers/blob/e50492284a5e8ef2f88c3c244e484d3986c9887e/custom_components/tech/sensor.py#L1019

but Tech API is returning also useful information about `batteryLevel` and `signalStrength` which should be represented into Home Assistant

```json
 {
      "id": 8003,
      "parentId": 0,
      "type": 1,
      "menuId": 0,
      "orderId": null,
      "visibility": true,
      "params": {
        "description": "Temperature sensor",
        "workingStatus": true,
        "txtId": 795,
        "value": 104,
        "batteryLevel": 100,
        "signalStrength": 29
      }
    }
```

**Comment by anarion80** [comment]
Adding this as entity attributes is easy:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/e725c22b-d464-4675-8fc7-50b33f2cce69)

The demo account only has one such tile, so if you can test on your controller: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/tree/feat_76 that would be great.

Adding as separate entities would be more involved, so please explain your expectation.

**Comment by daroga0002** [comment]
I checked and it is visible as:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/20227477/12c00b24-d8c8-40b0-8bc4-78e7e5e66687)


So it is not the best for me

I have created branch  https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/77

and now I see:

devices view:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/20227477/709f0614-998a-4ceb-bba4-05c4c1416f99)


device details:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/20227477/6c08bde4-180a-4f77-a433-58cca94fabbb)



entities:
![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/20227477/9f69a00d-1416-46b2-b29b-9bd4c6fd1933)




Could you look into this.
