### ISSUE TITLE
Czujniki okien

### ISSUE THREAD

**Issue by wusiu** [mariusz-ostoja-swierczynski/tech-controllers#94]
### The request

Na wstępie chciałbym podziękować za zaangażowanie wszystkim twórcom. Rozwój integracji idzie błyskawicznie. Dobra robota.

Wracając do tematu. Czy mógłby ktoś zaimplementować odczyt czujników okien?
Któraś wersja dawnej integracji to umożliwia i sam z niej korzystam. Wnioskuję więc, że jest możliwe.

**Comment by anarion80** [comment]
Ogólnie pewnie można :) tylko potrzeba przykładów. Trzeba by złapać zawartość modułów przez zalogowanie się na https://emodul.pl i skopiowanie całego JSONa jak tutaj:

![image](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/2185791/c5fba5da-c926-41e0-b070-69e3c53bf89f)

(Oczywiście z usuniętymi danymi wrażliwymi).

**Comment by wusiu** [comment]
[TECH json.txt](https://github.com/user-attachments/files/15904746/TECH.json.txt)

A tak przy okazji to fajną encją była by informacja o alarmie w konkretnej strefie (słaba bateria czy inna awaria którą sygnalizuje emodul): [zoneState] => noAlarm

**Comment by anarion80** [comment]
@wusiu I added a first attempt with window sensors: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/tree/feature_94. This is all "blind" coding though, without access to a system with real window sensors. 

So if you can please get the new version from here: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/archive/refs/heads/feature_94.zip, and test it with debug enabled.

**Comment by wusiu** [comment]
![Zrzut ekranu 2024-06-20 230833](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/66217416/0e9d39dc-2651-4cc0-b522-f745b26ae526)
![Zrzut ekranu 2024-06-20 230955](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/66217416/6694e332-c3b4-477e-b379-c745155d37d6)

**Comment by wusiu** [comment]
W starej zmodyfikowanej wersji u mnie okna działają. Przesyłam pliki.

[tech.zip](https://github.com/user-attachments/files/15920264/tech.zip)

**Comment by anarion80** [comment]
Załączony plik wyciąga status okien z `minOneWindowOpen` czyli pewnie włącza jeśli jakiekolwiek okno jest otwarte. Tutaj powinniśmy mieć entity na każde okno osobo. Anyway, jak możesz to sprawdź nowszą wersję: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/archive/refs/heads/feature_94.zip

z włączonym debugiem.

**Comment by wusiu** [comment]
Sensory nadal bez zmian ("nieznany")

log: 
[home-assistant_tech_2024-06-21T21-28-06.159Z.log](https://github.com/user-attachments/files/15933955/home-assistant_tech_2024-06-21T21-28-06.159Z.log)

**Comment by anarion80** [comment]
Ok, no to ostatni raz: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/archive/refs/heads/feature_94.zip

**Comment by wusiu** [comment]
Działa, ale aktualizuje stan tylko podczas uruchamiania integracji. Później pozostaje bez zmian, podczas gdy inne encje zmieniają wartość.

**Comment by anarion80** [comment]
Ok, najnowsza wersja już powinna działać: https://github.com/mariusz-ostoja-swierczynski/tech-controllers/archive/refs/heads/feature_94.zip

ALE! Trzeba pamiętać, że to jest integracja cloud polling i w tej chwili SYNC_INTERVAL jest 60 sekund, więc nie nadaje się do śledzenia natychmiastowych zmian stanu jak przy lokalnych połączeniach.

**Comment by wusiu** [comment]
Działa. Dzięki. Aktualizacja stanu następuje po około 40-50 sekundach. Akceptowalne.
