### ISSUE TITLE
[Feat]: Add zone alarm status

### ISSUE THREAD

**Issue by anarion80** [mariusz-ostoja-swierczynski/tech-controllers#96]
### The request

Consider adding binary sensors for zone alarm status in each zone (`'zoneState': 'noAlarm'`):

```json
'zone': {
            'id': 120,
            'parentId': 99,
            'time': '2024-06-21T23:20:50.618888',
            'duringChange': False,
            'index': 0,
            'currentTemperature': 255,
            'setTemperature': 220,
            'flags': {
                'relayState': 'off',
                'minOneWindowOpen': False,
                'algorithm': 'heating',
                'floorSensor': 0,
                'humidityAlgorytm': 0,
                'zoneExcluded': 0
            },
            'zoneState': 'noAlarm',
            'signalStrength': 70,
            'batteryLevel': 79,
            'actuatorsOpen': 0,
            'humidity': -2,
            'visibility': True
        },
```

**Comment by daroga0002** [comment]
when Alarm triggers?

**Comment by anarion80** [comment]
I have no idea yet :) I will wait until my remote temperature sensor in the garage loses connectivity to check what is then reported.

**Comment by wusiu** [comment]
Z tego co pamiętam jak testowałem to alarm zmienia stan gdy w którejś strefie pojawi się problem (słaba bateria, brak łączności). Analogicznie w emodulu wyświetla się czerwony wykrzyknik przy strefie z problemem.

**Comment by daroga0002** [comment]
I have a wireless thermostats and when I pull out batteries from one of them and wait few minutes there is no change in emodul and `zoneState` doesnt change at all.

Same was when batteries become discharged in past, the only difference was that zone go into off mode and I was not able to enable it

**Comment by wusiu** [comment]
Sprawdziłem na czujniku okna. Przed wyjęciem baterii było "noAlarm", a po wyjęciu "noCommunication".

![1](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/66217416/023665e3-13e4-4739-ac85-809966249918)
![2](https://github.com/mariusz-ostoja-swierczynski/tech-controllers/assets/66217416/d7527935-6371-421f-87c9-48e0ccf30fa1)

**Comment by wusiu** [comment]
To samo dzieje się w zmiennej "zoneState" po wyjęciu baterii z regulatora temperatury. Siłowniki też mają parametr "state". Była by to fajna opcja gdyby te dane dało się wyciągnąć chociażby jako atrybut, jak obecnie są podawane siła sygnału i bateria w siłownikach.

**Comment by daroga0002** [comment]
> To samo dzieje się w zmiennej "zoneState" po wyjęciu baterii z regulatora temperatury

I have done same, for 30 minutes nothing has changed in API output.

I am using https://tech-controllers.com/p/eu-r-8pb-plus
