### ISSUE TITLE
[Bug]: Cannot login to Tech Sterowniki account

### ISSUE THREAD

**Issue by marcinwrobel1984** [mariusz-ostoja-swierczynski/tech-controllers#97]
### The problem

Hi all,
I have a problem with login to Tech Sterowniki account. When I want to configure service I got error: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tech/__init__.py", line 61, in async_setup_entry
    await assets.load_subtitles(language_code, Tech(websession, user_id, token))
  File "/config/custom_components/tech/assets.py", line 25, in load_subtitles
    TRANSLATIONS = await api.get_translations(language)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tech/tech.py", line 190, in get_translations
    result = await self.get(path)
             ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tech/tech.py", line 73, in get
    raise TechError(response.status, await response.text())
custom_components.tech.tech.TechError: (400, '{"error":"Bad Request"}')

Can you please take a look?

### What version of Tech Controllers integration has the issue?

2.0.0

### What version of Home Assistant Core has the issue?

core-2024.7.3

### What was the last working version of Tech Controller integration?

2.0.0

**Comment by daroga0002** [comment]
if you got a special characters in password it can cause issue. Please try latest version 2.3.1 


(password handling was fixed in https://github.com/mariusz-ostoja-swierczynski/tech-controllers/pull/78)
